version: '3.7'

services:
  roman-numeral-app-container:
    image: roman-numeral-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: roman-numeral-app-container

  prom:
    image: prom/prometheus:v2.9.2
    volumes:
      - ./prom.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - roman-numeral-app-container
    container_name: prom

  grafana:
    image: grafana/grafana:6.1.4
    ports:
      - "3000:3000"
    depends_on:
      - prom
    container_name: grafana

